Add support for translations in our SPA
newfold-labs/wp-module-onboarding pull request #226
Opened 2023-05-01 08:04 UTC by arunshenoy99

2023-05-04 10:47 UTC, Yashita101 requested changes

2023-05-04 10:51 UTC, arunshenoy99 commented on src/OnboardingSPA/pages/Steps/TopPriority/stylesheet.scss
>  .info-button-top-priority {
Yes, we do else the alignment of text on the top priority subtext changes compared to trunk.

2023-05-05 07:45 UTC, arunshenoy99 commented on src/OnboardingSPA/pages/Steps/TopPriority/stylesheet.scss
>  .info-button-top-priority {
Pushed the removal, thanks @Yashita101

2023-05-05 08:23 UTC, Yashita101 approved these changes

2023-05-10 06:48 UTC, merged