Add Support for WordPress 6.3
newfold-labs/wp-module-onboarding pull request #272
Opened 2023-08-02 08:45 UTC by arunshenoy99

2023-08-04 12:39 UTC, officiallygod approved these changes
Everything looks good and seems to be working, just getting some logs when using this on WP 6.2. 
I did QA also and looks good to me, Thanks

2023-08-04 14:38 UTC, Yashita101 requested changes

2023-08-04 15:18 UTC, arunshenoy99 commented on src/OnboardingSPA/utils/global-styles/use-global-styles-output.js
> +		if ( requiredSettings.styles.blocks[ blockType.name ]?.css ) {
If that doesn't exist, then I am pretty sure we will not reach this block of code.

2023-08-04 15:19 UTC, arunshenoy99 commented
> Everything looks good and seems to be working, just getting some logs when using this on WP 6.2. I did QA also and looks good to me, Thanks

Thanks! @officiallygod

2023-08-08 09:46 UTC, Yashita101 approved these changes

2023-08-08 09:46 UTC, merged