Renamed typography to fonts
newfold-labs/wp-module-onboarding pull request #298
Opened 2023-08-29 06:19 UTC by girish-lokapure

PRESS2-1070 : Replace technically accurate "typography" with more commonly understood "fonts"

2023-08-30 12:04 UTC, officiallygod requested changes

2023-08-30 12:04 UTC, officiallygod commented on src/OnboardingSPA/components/Drawer/DrawerPanel/index.js
> +	// eslint-disable-next-line no-unused-vars
Why are we still using this state? Please check and remove it if possible, I don't see any issue.

2023-08-30 12:04 UTC, officiallygod commented on src/OnboardingSPA/components/Drawer/DrawerPanel/index.js
> +	// eslint-disable-next-line no-unused-vars
Same, Let's not use things we don't need, Thanks.

2023-08-30 12:04 UTC, officiallygod commented on src/OnboardingSPA/components/Drawer/DrawerPanel/index.js
> +		// eslint-disable-next-line jsx-a11y/no-static-element-interactions
Let us do this like we have done [here](https://github.com/newfold-labs/wp-module-onboarding/blob/4406cb9de1ef268935d340ed60217c3e8350acd4/src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js#L238C6-L241C51).

2023-08-31 10:53 UTC, girish-lokapure commented on includes/Data/Events.php
> +		'fonts_selected'              => true,
Hiive needs to be updated about the same

2023-09-01 07:29 UTC, officiallygod approved these changes
LGTM

2023-09-05 06:23 UTC, arunshenoy99 approved these changes
Should we get the `languages/wp-module-onboarding.pot` file? Seeing merge conflicts as well @girish-lokapure. Rest looks good, let's take care of these before merging

2023-09-05 06:40 UTC, officiallygod commented
> Should we get the `languages/wp-module-onboarding.pot` file updated? Seeing merge conflicts as well @girish-lokapure. Rest looks good, let's take care of these before merging

Looks like we need the pot file to be updated cause the text strings do change.

2023-09-13 13:53 UTC, girish-lokapure commented
> Should we get the `languages/wp-module-onboarding.pot` file updated? Seeing merge conflicts as well @girish-lokapure. Rest looks good, let's take care of these before merging

this is done

2023-09-18 05:03 UTC, arunshenoy99 reviewed
Looks good, @girish-lokapure. Let's hold off on merging this until we have a stable HostGator release.

2023-09-27 17:56 UTC, girish-lokapure commented
@arunshenoy99 please review the dependency module as well:
https://github.com/newfold-labs/wp-module-onboarding-data/pull/4

2023-09-28 10:20 UTC, arunshenoy99 approved these changes

2023-10-05 05:13 UTC, merged

2023-10-05 05:21 UTC, arunshenoy99 commented
We need to fix the lint on this.