PRESS2-1376 Add/sitegen socialmedia
newfold-labs/wp-module-onboarding pull request #366
Opened 2023-11-15 13:08 UTC by girish-lokapure

![Screenshot Capture - 2023-11-15 - 18-37-03](https://github.com/newfold-labs/wp-module-onboarding/assets/10253048/9907ee72-3989-4133-81e6-a4089e6e0b1b)
![Screenshot Capture - 2023-11-24 - 14-59-26](https://github.com/newfold-labs/wp-module-onboarding/assets/10253048/795e0ced-fefe-4a59-a4ce-98a4db8620c4)

2023-11-20 08:09 UTC, officiallygod reviewed
Please do merge the latest [enhance/ai-onboarding](https://github.com/newfold-labs/wp-module-onboarding/tree/enhance/ai-onboarding) branch as I think there are numerous changes.

2023-11-20 08:09 UTC, officiallygod commented on src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
> +						<button className="nfd-onboarding-step--site-gen__social-media__contain__containright__button ">
I think the icon is supposed to be white? 
<img width="1617" alt="Screenshot 2023-11-20 at 1 18 49 PM" src="https://github.com/newfold-labs/wp-module-onboarding/assets/48691514/5c033abf-42aa-46b4-b437-b18dd26961cf">

2023-11-20 08:09 UTC, officiallygod commented on src/OnboardingSPA/steps/SiteGen/SocialMedia/stylesheet.scss
> +				border: 1.25px dashed var(--nfd-onboarding-site-logo-border);
Should this be dotted?
<img width="1617" alt="Screenshot 2023-11-20 at 1 18 49 PM" src="https://github.com/newfold-labs/wp-module-onboarding/assets/48691514/4ed19d16-d156-4cc5-8285-fbe87b04dcb5">

2023-11-20 08:09 UTC, officiallygod commented on src/OnboardingSPA/steps/SiteGen/SocialMedia/contents.js
> +		facebookdesc: __(
Let's keep camelCase consistent

2023-11-20 08:09 UTC, officiallygod commented on src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
> +						callback={ () => resetSiteLogo() }
Why do we need this?

2023-11-20 08:09 UTC, officiallygod commented on src/OnboardingSPA/styles/app.scss
> +@import "../steps/SiteGen/SocialMedia/stylesheet.scss";
We can omit the extension.

2023-11-24 08:45 UTC, diwanshuster requested changes
Can you check for mobile responsiveness as well?

2023-11-24 09:35 UTC, girish-lokapure commented
> Can you check for mobile responsiveness as well?

done

2023-11-28 08:23 UTC, diwanshuster approved these changes
LGTM

2023-11-28 08:25 UTC, merged