Adding simple customer promt screen
newfold-labs/wp-module-onboarding pull request #382
Opened 2023-12-05 12:49 UTC by girish-lokapure

2023-12-13 10:51 UTC, officiallygod requested changes
https://github.com/newfold-labs/wp-module-onboarding/assets/48691514/c0e247c4-40fb-405b-8c1c-515d7a7012d4

- There is a BUG that needs to be addressed and THE DATA IS NOT SAVED.

![Screenshot 2023-12-13 at 3 49 21 PM](https://github.com/newfold-labs/wp-module-onboarding/assets/48691514/4f8b864d-c779-42dd-8da4-fd94414de394)

- Please add Bottom Margin in Mobile View.

![Screenshot 2023-12-13 at 3 56 14 PM](https://github.com/newfold-labs/wp-module-onboarding/assets/48691514/48442e02-578f-4d58-96a9-2b98508eb578)

- NEXT Needs to be disabled as it was done on the Site Details page.

![Screenshot 2023-12-13 at 3 48 21 PM](https://github.com/newfold-labs/wp-module-onboarding/assets/48691514/0447670a-c0c2-45d1-b37f-81f4e3f84893)

- I think the Text should be WHITE and not gray after the user types it.

![Screenshot 2023-12-13 at 3 51 39 PM](https://github.com/newfold-labs/wp-module-onboarding/assets/48691514/de8fe7b5-2f98-4771-b5de-4d1a15c9dd28)

- Let's remove unnecessary spaces and fix typos to make it better formatted for the user.

Thanks.

2023-12-13 10:51 UTC, officiallygod commented on src/OnboardingSPA/steps/SiteGen/SiteDetails/walkthrough/index.js
> +		);
Let's change the classes with React code using `classnames` and not Directly manipulate the DOM.

2023-12-18 12:28 UTC, girish-lokapure commented on src/OnboardingSPA/components/Button/ButtonWhite/SiteGen/index.js
> +			className={ classNames( className ) }
we will be having multiple classnames

2023-12-18 12:48 UTC, girish-lokapure commented on src/OnboardingSPA/steps/SiteGen/SiteDetails/walkthrough/index.js
> +	const [ customerInputUnique, setCustomerInputUnique ] = useState();
I think this is fine, the load/lag was due to the api call which has been fixed

2023-12-19 12:05 UTC, arunshenoy99 requested changes
![image](https://github.com/newfold-labs/wp-module-onboarding/assets/38878906/aeafba08-63bc-48fe-aa6b-d6189105c777)
Bug: The placeholder text appears in white, giving the impression that the input is filled. Can we match it to Figma's specifications?

https://github.com/newfold-labs/wp-module-onboarding/assets/38878906/83036744-0055-4370-a031-99a975f84113
Bug: The selected button grays out, giving a false indication that another option was selected. Can we align this with Figma's specifications?

![image](https://github.com/newfold-labs/wp-module-onboarding/assets/38878906/b0fded39-399f-41e3-904c-6e6fefd739ce)
Bug: Can we add some padding between the text and the textarea border?

![image](https://github.com/newfold-labs/wp-module-onboarding/assets/38878906/62e16e11-f104-4b2c-9048-201ad17948dd)
Bug: I cannot proceed to the next screen when in this state. Additionally, the highlighted white color suggests 'Yes' was selected, but I have actually chosen 'No,' which is now grayed out.

![image](https://github.com/newfold-labs/wp-module-onboarding/assets/38878906/cdecaa0d-07cc-4c6f-8f45-c3847fc502bf)
Could we add an appropriate placeholder for this input?

https://github.com/newfold-labs/wp-module-onboarding/assets/38878906/01732971-2644-4187-8545-055ab6f27e4c
When we go back, should we return to the simple prompt screen or the welcome screen?

![image](https://github.com/newfold-labs/wp-module-onboarding/assets/38878906/ab8cec5f-603c-4b8b-921d-f06acac4f76b)
Bug: In the mobile view, the textarea blurs into the footer. Can we add some spacing or adjust the layout to address this issue?

I will review more once these issues are addressed. Thanks, @girish-lokapure.

2023-12-21 10:57 UTC, girish-lokapure commented on includes/RestApi/SiteGenController.php
> +	}
moved to onboarding data

2023-12-21 11:02 UTC, girish-lokapure commented on src/OnboardingSPA/steps/SiteGen/SiteDetails/contents.js
> +		),
As discussed this is not required now

2024-01-09 12:26 UTC, girish-lokapure commented
- fixed Flow data API 
- Input sanitized and trimmed
- Modified Color schema for light mode
- Fixed navigation “Next” button issues

2024-01-15 06:53 UTC, arunshenoy99 approved these changes

2024-01-15 20:10 UTC, arunshenoy99 approved these changes

2024-01-15 20:10 UTC, merged